# Python Libraries: Numpy

Install the module: __pip install numpy__

## Create an array

There are several ways of creating and filling an array!

In [4]:
import numpy as np #import library

list = [1,2,3,4,5] 
print(list) 
array = np.array([1,2,3,4,5]) 
print(array)

print(list*2)
print(array*2)


[1, 2, 3, 4, 5]
[1 2 3 4 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [7]:
print(np.arange(10)) 
print(np.zeros((10,)))              
print(np.ones((2,3)))             
print(np.full((5,), 7))
print(np.eye(4))               
print(np.random.random((1,4)))  
print(np.random.random_integers(-10, 10, (4,4)))  


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[7 7 7 7 7]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.34400512 0.04234007 0.99449629 0.08878798]]
[[ -9   1  -9  10]
 [  9 -10   9   3]
 [ 10  -9  -2   5]
 [  6   6   5  10]]


## New datatypes
By default Python has string, integer, float, boolean and complex as datatypes, but Numpy extends that list and refers to them with a single character:
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

Checking data types is always done by the built-in function __type() __, but due to the limitation of arrays consisting of elements of the same data type, we can also get the data type of the elements with the property __dtype__. Converting between two data types is quite easy with __astype()__ (only if it is convertable, otherwise you will get an error) and getting information about the dimensions is done by properties __shape__ and __ndim__. Note that your array is fixed size once created, but you can easily transform it in anoher shape with different dimensions by __reshape()__

In [44]:
array = np.array([1, 2, 3, 4, 5, 6,7,8])
print(array)

print(type([1, 2, 3, 4, 5]))    #list
print(type(array))              #mNumpy array
print(array.dtype)
new_array = array.astype('f')
print(new_array)
print(new_array.dtype)

print("SHAPE: " + str(array.shape) + " DIM: " + str(array.ndim))

array_2D = np.reshape(array, (4,2))
print(array_2D)
print("SHAPE: " + str(array_2D.shape) + " DIM: " + str(array_2D.ndim))
array_3D = np.reshape(array, (2,2,2))
print(array_3D)
print("SHAPE: " + str(array_3D.shape) + " DIM: " + str(array_3D.ndim))

[1 2 3 4 5 6 7 8]
<class 'list'>
<class 'numpy.ndarray'>
int32
[1. 2. 3. 4. 5. 6. 7. 8.]
float32
SHAPE: (8,) DIM: 1
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
SHAPE: (4, 2) DIM: 2
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
SHAPE: (2, 2, 2) DIM: 3


## A slice of array

Slicing in python means taking elements from one given (start)index to another given (end)index like this \[start: end\]. To define a step size, just add it to the brackets as follows \[start: end: step\]. If you don't pass anything, it's considered to be 0 at the start, full length at the end, and step as 1. It quite useful to know these shortcodes. Also remember that you can use negative indexes.

In [12]:
a = np.arange(8)**3    # exponent 3 --> 0^3 1^3 2^3 3^3 ...
print(a)
print(a[2:5])
print(a[:4])           
print(a[4:])
a[::3] = -1         
print(a)   
print(a[::-1])  #reverse          
print(a[1::2])  # odd indexes                

[  0   1   8  27  64 125 216 343]
[ 8 27 64]
[ 0  1  8 27]
[ 64 125 216 343]
[ -1   1   8  -1  64 125  -1 343]
[343  -1 125  64  -1   8   1  -1]
[  1  -1 125 343]


## Array operations

Numpy has tons of methods to perform any kind of operation on an array, here we discuss just a few that might come in handy!

In [116]:
a = np.arange(0,10)     #exclusive end
b = np.arange(9,-1,-1)
print(a)
print(b)
c = a-b
print(c)
print(c<0)
print(np.where(c<0))
c %= 3
print(c)
print(np.add(a, c))
print(np.where(a%2==1,a+1,a)) #check condition, if condition == true, a+1, else a

b = np.reshape(b,(2,5))
print(b)
print(b.sum(axis=0))         # sum of each column
print(b.min(axis=1))         # min of each row
print(b.cumsum(axis=1))      # cumulative sum along each row
print(np.sqrt(b))

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[-9 -7 -5 -3 -1  1  3  5  7  9]
[ True  True  True  True  True False False False False False]
(array([0, 1, 2, 3, 4], dtype=int32),)
[0 2 1 0 2 1 0 2 1 0]
[0 3 3 3 6 6 6 9 9 9]
[ 0  2  2  4  4  6  6  8  8 10]
[[9 8 7 6 5]
 [4 3 2 1 0]]
[13 11  9  7  5]
[5 0]
[[ 9 17 24 30 35]
 [ 4  7  9 10 10]]
[[3.         2.82842712 2.64575131 2.44948974 2.23606798]
 [2.         1.73205081 1.41421356 1.         0.        ]]


In [127]:
import numpy as np

a=np.random.randint(4, size=9)
print(a)
print(np.reshape(a,(3,3)))

[1 2 3 1 1 0 1 0 0]
[[1 2 3]
 [1 1 0]
 [1 0 0]]


## Practice makes perfect
### Random matrix
Create a x*x matrix filled with values ranging from 0 to x, __x is given by user__
eg: x = 3 
```
[[1 2 3]
 [1 1 0]
 [1 0 0]]
```

- Find indices of non-zero elements
- Find all occurences of x
- Transform the even number to odd ones
- Create a new matrix with the same credentials
- Find common items between the two matrices
- Remove all common items in the second matrix
- Transform the first array, colums become rows and vice versa
- Randomize the second matrix again
- Sort the second matrix
- ...
